# Generated by Django 3.0.5 on 2020-05-17 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('subject', models.CharField(max_length=140)),
                ('template_name', models.CharField(max_length=140)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Sender')),
            ],
        ),
        migrations.CreateModel(
            name='EmailToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dj-waiting', 'Waiting On Celery'), ('sent', 'Mandrill - Sent'), ('queued', 'Mandrill - En Cola'), ('scheduled', 'Mandrill - Agendado'), ('rejected', 'Mandrill - Rechazado'), ('invalid', 'Mandrill - Invalido')], default='dj-waiting', max_length=50)),
                ('reject_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.TransactionalEmail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
