# Generated by Django 3.0.5 on 2020-05-17 23:16

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_remove_transactionalemail_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalemail',
            name='body',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
